version: '3.6'
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile_nginx
    ports: 
      - 8100:80
    volumes: 
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - laravel
      - mysql
  laravel:
    build:
      context: .
      dockerfile: Dockerfile_php
    environment: 
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:oQU5xFmAkzAydYX2r0Uvj2eYZDRsWOgZviYCmBE8g20=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8100
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_PASSWORD: laravel-pass
      DB_USERNAME: laravel
      DB_DATABASE: laravel
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: laravel-pass
      MYSQL_USER: laravel
      MYSQL_DATABASE: laravel
    restart: unless-stopped
  redis:
    image: redis:6.0
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 8102:8001
