# build
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run prod


# Production
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/public /var/www/laravel/public
# CMD ["nginx", "-g", "daemon off;"]
